stages:
  extract:
    cmd: python src/dvc_extractor.py
    deps:
    - src/dvc_extractor.py
    outs:
    - data/brinvesting_news_stage.parquet
    - data/bcb_real2dolar_stage.parquet
    - data/bcb_selic_input.parquet
  transform:
    cmd: python src/dvc_transformer.py data/bcb_selic_input.parquet
    deps:
    - data/bcb_selic_input.parquet
    - src/dvc_transformer.py
    outs:
    - data/bcb_selic_stage.parquet
  load:
    cmd: python src/dvc_loader.py data/brinvesting_news_stage.parquet data/bcb_real2dolar_stage.parquet data/bcb_selic_stage.parquet
    deps:
    - data/brinvesting_news_stage.parquet
    - data/bcb_real2dolar_stage.parquet
    - data/bcb_selic_stage.parquet
    - src/dvc_loader.py
